# This is a basic workflow to help you get started with Actions

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run typescript check
        run: npx tsc --noEmit

      - name: Build the web bundle
        run: npx parcel build index.html

      - uses: actions/checkout@v2
        with:
          repository: anoop901/anoop901.github.io
          path: anoop901.github.io

      - name: Copy web bundle to pages repository
        run: |
          mkdir -p anoop901.github.io/mandala-generator
          cp dist/* anoop901.github.io/mandala-generator

      - name: Commit to pages repository
        run: |
          cd anoop901.github.io
          git config user.email "anoop901@gmail.com"
          git config user.name "Anoop Naravaram"
          git add mandala-generator
          git commit -m "New release of mandala-generator"
          git push
